apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: apisix-vault-auth
  namespace: ingress-apisix
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: apisix-vso
    serviceAccount: default
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: apisix-admin-secret-sync
  namespace: ingress-apisix
spec:
  type: kv-v2
  mount: secret
  path: platform/apisix/dev
  destination:
    name: apisix-admin-credentials
    create: true
    transformation:
      templates:
        admin_key:
          text: '{{ .Secrets.admin_key }}'
  refreshAfter: 1h
  vaultAuthRef: apisix-vault-auth
