apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  source:
    repoURL: https://charts.kargo.io
    chart: kargo
    targetRevision: 1.9.5
    helm:
      values: |
        api:
          adminAccount:
            enabled: true
            passwordHash: ""    # Generar con: htpasswd -bnBC 10 "" admin | tr -d ':\n'
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
