apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-pro
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.34.0
    helm:
      values: |
        controlPlane:
          distro:
            k8s:
              enabled: true
          statefulSet:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
            scheduling:
              nodeSelector:
                vcluster: pro
              tolerations:
                - key: vcluster
                  value: pro
                  effect: NoSchedule
        sync:
          toHost:
            ingresses:
              enabled: true
          fromHost:
            secrets:
              enabled: true
              mappings:
                byName:
                  "keycloak/keycloak-db-secret": "keycloak/keycloak-db-secret"
                  "keycloak/keycloak-admin-secret": "keycloak/keycloak-admin-secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-pro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
