apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak-vault-auth
  namespace: keycloak
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: keycloak
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-db-secret-sync
  namespace: keycloak
spec:
  type: kv-v2
  mount: secret
  path: dev/keycloak
  destination:
    name: keycloak-db-secret
    create: true
    transformation:
      templates:
        password:
          text: '{{ .Secrets.db_password }}'
        username:
          text: 'keycloak'
        postgres-password:
          text: '{{ .Secrets.db_password }}'
  refreshAfter: 60s
  vaultAuthRef: keycloak-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-admin-secret-sync
  namespace: keycloak
spec:
  type: kv-v2
  mount: secret
  path: dev/keycloak
  destination:
    name: keycloak-admin-secret
    create: true
    transformation:
      templates:
        admin-password:
          text: '{{ .Secrets.admin_password }}'
  refreshAfter: 60s
  vaultAuthRef: keycloak-vault-auth
