apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-postgres
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git
    targetRevision: HEAD
    path: gitops/platform/components/n8n-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
