{{- range .Values.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .path }}
  destination:
    name: {{ .destination }}
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ $.Release.Name }}-vault-auth
{{- end }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Release.Name }}-vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Release.Name }}
    serviceAccount: {{ .Release.Name }}
