apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    helm:
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
                isDefault: true
        admin:
          existingSecret: grafana-admin-secret
          userKey: admin-user
          passwordKey: admin-password
        envValueFrom:
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-admin-secret
              key: oauth-client-secret
        grafana.ini:
          server:
            root_url: "https://grafana-dev.local.lp"
          auth:
            disable_login_form: false
          auth.generic_oauth:
            enabled: true
            name: Keycloak
            allow_sign_up: true
            client_id: grafana
            scopes: openid email profile
            auth_url: "https://keycloak-dev.local.lp/realms/cloudframe/protocol/openid-connect/auth"
            token_url: "https://keycloak-dev.local.lp/realms/cloudframe/protocol/openid-connect/token"
            api_url: "https://keycloak-dev.local.lp/realms/cloudframe/protocol/openid-connect/userinfo"
        service:
          type: ClusterIP
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL   # Busca ConfigMaps con dashboards en todos los namespaces
          datasources:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
