apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/systtekcloud/gitops-base-platform.git
    targetRevision: HEAD
    path: charts/platform-bootstrap/karpenter-apps
    helm:
      values: |
        clusterName: eks-vcluster-dev
        nodeRoleName: eks-vcluster-eks-node-role
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
