apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-apps
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git
    targetRevision: HEAD
    path: gitops/vclusters/apps
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
