apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-pro
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kargo.akuity.io/authorized-stage: demo-app:pro
spec:
  project: cloudframe-platform
  source:
    repoURL: https://gitlab.com/api/v4/projects/81438572/packages/helm/stable
    chart: demo-app
    targetRevision: 1.0.0
  destination:
    server: https://vcluster-pro.vcluster-pro.svc.cluster.local:443
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
