apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: httpbin
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git
      - name: appFile
        value: gitops/vclusters/apps/httpbin/application-dev.yaml
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: ./repo/${{ vars.appFile }}
          updates:
          - key: spec.source.targetRevision
            value: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: "chore: promote httpbin ${{ chartFrom(\"https://matheusfm.dev/charts\", \"httpbin\").Version }} to dev"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: httpbin-dev
            namespace: argo
            sources:
            - repoURL: https://matheusfm.dev/charts
              chart: httpbin
              desiredRevision: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
              updateTargetRevision: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre
  namespace: httpbin
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git
      - name: appFile
        value: gitops/vclusters/apps/httpbin/application-pre.yaml
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: ./repo/${{ vars.appFile }}
          updates:
          - key: spec.source.targetRevision
            value: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: "chore: promote httpbin ${{ chartFrom(\"https://matheusfm.dev/charts\", \"httpbin\").Version }} to pre"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: httpbin-pre
            namespace: argo
            sources:
            - repoURL: https://matheusfm.dev/charts
              chart: httpbin
              desiredRevision: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
              updateTargetRevision: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pro
  namespace: httpbin
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: httpbin
    sources:
      stages:
      - pre
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git
      - name: appFile
        value: gitops/vclusters/apps/httpbin/application-pro.yaml
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: ./repo/${{ vars.appFile }}
          updates:
          - key: spec.source.targetRevision
            value: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: "chore: promote httpbin ${{ chartFrom(\"https://matheusfm.dev/charts\", \"httpbin\").Version }} to pro"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: httpbin-pro
            namespace: argo
            sources:
            - repoURL: https://matheusfm.dev/charts
              chart: httpbin
              desiredRevision: ${{ chartFrom("https://matheusfm.dev/charts", "httpbin").Version }}
              updateTargetRevision: true
