apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-operator
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster-platform
    targetRevision: 4.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
