apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-dev-local-lp-cert
  namespace: observability
spec:
  secretName: grafana-dev-local-lp-tls
  dnsNames:
    - grafana-dev.local.lp
  issuerRef:
    name: lab-local-ca
    kind: ClusterIssuer
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: grafana-dev-local-lp
  namespace: observability
spec:
  hosts:
    - grafana-dev.local.lp
  ingressClassName: apisix
  secret:
    name: grafana-dev-local-lp-tls
    namespace: observability
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: grafana-route
  namespace: observability
spec:
  ingressClassName: apisix
  http:
    - name: grafana
      match:
        hosts:
          - grafana-dev.local.lp
        paths:
          - /*
      backends:
        - serviceName: grafana
          servicePort: 80
