apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana-vault-auth
  namespace: observability
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: grafana
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-secret-sync
  namespace: observability
spec:
  type: kv-v2
  mount: secret
  path: dev/grafana
  destination:
    name: grafana-admin-secret
    create: true
    transformation:
      templates:
        admin-user:
          text: 'admin'
        admin-password:
          text: '{{ .Secrets.admin_password }}'
        oauth-client-secret:
          text: '{{ .Secrets.oauth_client_secret }}'
  refreshAfter: 60s
  vaultAuthRef: grafana-vault-auth
