apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kargo-admin-secret-sync
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: kv-v2
  mount: secret
  path: platform/kargo/admin
  destination:
    name: kargo-admin-secret
    create: true
  refreshAfter: 1h
  vaultAuthRef: kargo-vault-auth
