apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: demo-app-registry-credentials
  namespace: kargo
spec:
  type: kv-v2
  mount: secret
  path: platform/kargo/gitlab
  destination:
    name: kargo-gitlab-registry
    create: true
    labels:
      kargo.akuity.io/cred-type: helm
    transformation:
      templates:
        repoURL:
          text: 'oci://registry.gitlab.com/eks-vcluster-platform/gitops-base-platform'
        username:
          text: '{{ .Secrets.username }}'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 1h
  vaultAuthRef: kargo-vault-auth
