apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: demo-app-vault-auth
  namespace: demo-app
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: demo-app-vso
    serviceAccount: default
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: demo-app-gitlab-credentials
  namespace: demo-app
spec:
  type: kv-v2
  mount: secret
  path: platform/kargo/gitlab
  destination:
    name: kargo-gitlab-credentials
    create: true
    labels:
      kargo.akuity.io/cred-type: git
    transformation:
      templates:
        repoURL:
          text: 'https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git'
        username:
          text: '{{ .Secrets.username }}'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 1h
  vaultAuthRef: demo-app-vault-auth
