apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-etcd
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cloudframe-platform
  source:
    repoURL: oci://registry-1.docker.io/cloudpirates
    chart: etcd
    targetRevision: 0.7.1
    helm:
      valuesObject:
        fullnameOverride: apisix-etcd
        replicaCount: 1
        auth:
          enabled: false
          peer:
            enabled: false
        persistence:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
