{{- if and .Values.vaultResources.enabled .Values.vaultResources.staticSecrets }}
{{- $defaultNamespace := include "cloudframe-platform.vaultDefaultNamespace" . -}}
{{- range .Values.vaultResources.staticSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ required "vaultResources.staticSecrets[].name is required" .name }}
  namespace: {{ default $defaultNamespace .namespace }}
  labels:
    {{- include "cloudframe-platform.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ required (printf "vaultResources.staticSecrets[%s].vaultAuthRef is required" .name) .vaultAuthRef }}
  mount: {{ required (printf "vaultResources.staticSecrets[%s].mount is required" .name) .mount | quote }}
  type: {{ required (printf "vaultResources.staticSecrets[%s].type is required" .name) .type | quote }}
  path: {{ required (printf "vaultResources.staticSecrets[%s].path is required" .name) .path | quote }}
  refreshAfter: {{ default "1m" .refreshAfter | quote }}
  hmacSecretData: {{ default true .hmacSecretData }}
  {{- with .version }}
  version: {{ . }}
  {{- end }}
  destination:
    create: {{ default true .destination.create }}
    name: {{ required (printf "vaultResources.staticSecrets[%s].destination.name is required" .name) .destination.name }}
    type: {{ default "Opaque" .destination.type }}
    {{- with .destination.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .destination.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .destination.transformation }}
    transformation:
      {{- with .excludes }}
      excludes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .templates }}
      templates:
        {{- range $templateName, $templateBody := . }}
        {{ $templateName }}:
          text: |
{{ $templateBody | nindent 12 }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
