{{- if and .Values.vaultResources.enabled .Values.vaultResources.serviceAccounts }}
{{- $defaultNamespace := include "cloudframe-platform.vaultDefaultNamespace" . -}}
{{- range .Values.vaultResources.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "vaultResources.serviceAccounts[].name is required" .name }}
  namespace: {{ default $defaultNamespace .namespace }}
  labels:
    {{- include "cloudframe-platform.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
