apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-github-credentials
  namespace: argo
spec:
  type: kv-v2
  mount: secret
  path: platform/argocd/github-ssh
  destination:
    name: repo-github-gitops-demo
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      templates:
        type:
          text: 'git'
        url:
          text: 'git@github.com:systtekcloud/gitops-argocd.git'
        sshPrivateKey:
          text: '{{ .Secrets.sshPrivateKey }}'
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
