apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-gitlab-pkg-credentials
  namespace: argo
spec:
  type: kv-v2
  mount: secret
  path: platform/argocd/gitlab-pkg
  destination:
    name: repo-gitlab-helm-pkg
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      templates:
        type:
          text: 'helm'
        url:
          text: 'https://gitlab.com/api/v4/projects/81438572/packages/helm/stable'
        username:
          text: '{{ .Secrets.username }}'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
