apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-gitlab-credentials
  namespace: argo
spec:
  type: kv-v2
  mount: secret
  path: platform/argocd/gitlab
  destination:
    name: repo-gitlab-gitops-base
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      templates:
        type:
          text: 'git'
        url:
          text: 'https://gitlab.com/eks-vcluster-platform/gitops-base-platform.git'
        username:
          text: '{{ .Secrets.username }}'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
