apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-gitlab-registry-credentials
  namespace: argo
spec:
  type: kv-v2
  mount: secret
  path: platform/argocd/gitlab-reg
  destination:
    name: repo-gitlab-registry
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      templates:
        type:
          text: 'helm'
        name:
          text: 'gitlab-registry'
        url:
          text: 'registry.gitlab.com/eks-vcluster-platform/gitops-base-platform'
        enableOCI:
          text: 'true'
        username:
          text: '{{ .Secrets.username }}'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
