apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://cloudpirates-io.github.io/helm-charts
    chart: keycloak
    targetRevision: 0.20.5
    helm:
      values: |
        keycloak:
          adminUser: admin
          existingSecret: keycloak-admin-secret
          secretKeys:
            adminPasswordKey: admin-password
          httpEnabled: true
          production: true
        database:
          type: postgres
          host: keycloak-postgresql.keycloak.svc.cluster.local
          port: "5432"
          name: keycloak
          username: keycloak
          existingSecret: keycloak-db-secret
          secretKeys:
            passwordKey: password
            usernameKey: username
        postgres:
          enabled: false
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
