apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://cloudpirates-io.github.io/helm-charts
    chart: keycloak
    targetRevision: 0.20.5
    helm:
      values: |
        replicaCount: 1
        keycloak:
          adminUser: admin
          existingSecret: keycloak-admin-secret
          secretKeys:
            adminPasswordKey: admin-password
          httpEnabled: true
          httpPort: 8080
          hostname: "https://keycloak-dev.local.lp"
          hostnameStrict: true
          proxyHeaders: xforwarded
          production: true
        database:
          type: postgres
          host: keycloak-postgresql.keycloak.svc.cluster.local
          port: "5432"
          name: keycloak
          username: keycloak
          existingSecret: keycloak-db-secret
          secretKeys:
            passwordKey: password
            usernameKey: username
        postgres:
          enabled: false
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 5Gi
          storageClass: "standard"
        extraEnvVars:
          - name: KC_HOSTNAME_DEBUG
            value: "true"
          - name: KC_SPI_THEME_CACHE_THEMES
            value: "false"
          - name: KC_SPI_THEME_STATIC_MAX_AGE
            value: "-1"
          - name: KC_LOG_CONSOLE_OUTPUT
            value: "json"
          - name: KC_LOG_CONSOLE_JSON_FORMAT
            value: "ecs"
          - name: KC_LOG_LEVEL
            value: "INFO,org.keycloak.events:DEBUG"
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
