apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-postgresql
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: cloudframe-platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.2
    helm:
      values: |
        global:
          imageRegistry: "oci.bitnami.com"
        auth:
          username: keycloak
          database: keycloak
          existingSecret: keycloak-db-secret
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
        primary:
          persistence:
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
