apiVersion: v1
kind: Secret
metadata:
  name: cluster-vcluster-pro
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd/clusters/vcluster-pro"
stringData:
  name: vcluster-pro
  server: https://vcluster-pro.vcluster-pro.svc.cluster.local:443
  config: |
    {"bearerToken": "<token>", "tlsClientConfig": {"insecure": true}}
