apiVersion: v1
kind: Secret
metadata:
  name: cluster-vcluster-pre
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd/clusters/vcluster-pre"
stringData:
  name: vcluster-pre
  server: https://vcluster-pre.vcluster-pre.svc.cluster.local:443
  config: |
    {"bearerToken": "<token>", "tlsClientConfig": {"insecure": true}}
