apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cluster-vcluster-pro
  namespace: argo
spec:
  type: kv-v2
  mount: secret
  path: argocd/clusters/vcluster-pro
  destination:
    name: cluster-vcluster-pro
    create: true
    labels:
      argocd.argoproj.io/secret-type: cluster
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
